In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/mnt/L-HDD/Public/dataset/splitted.csv", chunksize=5000000)

In [ ]:
for chunk in df:
    display(chunk)

,unique_id,id,time,type,x,y,hit_sound,repeat,length,spinner_time,...,path_41,path_42,path_43,path_44,path_45,path_46,path_47,path_48,path_49,path_50
0,2503294,1000309-0,4790.0,spinner,256,192,8,0,0.00000,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2503295,1000309-0,7603.0,circle,104,34,0,0,0.00000,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2503296,1000309-0,7759.0,circle,171,1,0,0,0.00000,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2503297,1000309-0,7915.0,circle,243,85,8,0,0.00000,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2503298,1000309-0,8071.0,circle,78,34,8,0,0.00000,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4999995,6236,2265991-0,310853.0,circle,300,45,8,0,0.00000,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4999996,6237,2265991-0,310944.0,slider,262,63,0,1,169.99999,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4999997,6238,2265991-0,311493.0,circle,306,148,0,0,0.00000,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4999998,6239,2265991-0,311676.0,slider,171,302,0,1,169.99999,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4999999,6240,2265991-0,312225.0,circle,414,205,8,0,0.00000,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
with open("/mnt/L-HDD/Public/dataset/splitted.csv", "r", newline="") as f:
    reader = csv.reader(f, delimiter=",")
    headers = next(reader)